#cloud-config
# ------------------------------------------------------------------------------
# OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
# ------------------------------------------------------------------------------
# Name.......: apache_webserver_http_ol8.yaml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
# Editor.....: Stefan Oehrli
# Date.......: 2024.10.18
# Revision...: --
# Purpose....: cloud-init configuration file for Apache web server (HTTP only)
# Notes......: This script configures Apache to serve HTTP content on port 80.
# Reference..: --
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------
package_update: true
package_upgrade: true

# Install Apache (httpd)
packages:
  - httpd

# Enable and start Apache service
runcmd:
  - systemctl enable httpd
  - systemctl start httpd

# Create a simple HTML page for testing HTTP
write_files:
  - path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to Apache!</title>
      </head>
      <body>
          <h1>Hello World</h1>
          <p>This is a simple HTTP page served by Apache on Oracle Linux 8</p>
      </body>
      </html>

# Open firewall for HTTP traffic (port 80)
runcmd:
  - firewall-cmd --add-service=http --permanent
  - firewall-cmd --reload

# Final message to show completion
final_message: "Apache HTTP server is installed and running!"
# --- EOF -------------------------------------------------------------------
