#cloud-config
# ------------------------------------------------------------------------------
# OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
# ------------------------------------------------------------------------------
# Name.......: apache_webserver_http_ol8.yaml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
# Editor.....: Stefan Oehrli
# Date.......: 2024.10.18
# Revision...: 0.12.0
# Purpose....: cloud-init configuration file for Apache web server (HTTP only)
# Notes......: This script configures Apache to serve HTTP content on port 80.
# Reference..: --
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------
package_update: true
package_upgrade: true

# Install Apache (httpd)
packages:
  - httpd

# Enable and start Apache service
# runcmd:
#   - systemctl enable httpd
#   - systemctl start httpd
runcmd:
  - date >> /var/log/cloud-init-debug.log
  - echo "Starting HTTPD enable" >> /var/log/cloud-init-debug.log
  - systemctl enable httpd || echo "Failed to enable httpd" >> /var/log/cloud-init-debug.log
  - date >> /var/log/cloud-init-debug.log
  - echo "Starting HTTPD service" >> /var/log/cloud-init-debug.log
  - systemctl start httpd || echo "Failed to start httpd" >> /var/log/cloud-init-debug.log
  - date >> /var/log/cloud-init-debug.log
  - echo "Opening firewall port 80" >> /var/log/cloud-init-debug.log
  - systemctl start firewalld || echo "Failed to start firewalld" >> /var/log/cloud-init-debug.log
  - firewall-cmd --add-service=http --permanent || echo "Failed to add firewall rule" >> /var/log/cloud-init-debug.log
  - firewall-cmd --reload || echo "Failed to reload firewall" >> /var/log/cloud-init-debug.log
  - date >> /var/log/cloud-init-debug.log


# Create a simple HTML page for testing HTTP
write_files:
  - path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to Apache!</title>
      </head>
      <body>
          <h1>Hello World</h1>
          <p>This is a simple HTTP page served by Apache on Oracle Linux 8</p>
      </body>
      </html>

# Open firewall for HTTP traffic (port 80)
runcmd:
  - firewall-cmd --add-service=http --permanent
  - firewall-cmd --reload

# Final message to show completion
final_message: "Apache HTTP server is installed and running!"
# --- EOF -------------------------------------------------------------------
